export {
  SLAM_WORKFLOW_JOB_TOPIC_NAME,
  SLAM_WORKFLOW_JOB_TOPIC_TYPE,
  SLAM_WORKFLOW_STATE_TOPIC_NAME,
  SLAM_WORKFLOW_STATE_TOPIC_TYPE,
} from './queryContracts'

export const SLAM_WORKFLOW_TOPIC_STALE_AFTER_MS = 5_000
